/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as PdJourneyRouteImport } from './routes/pd-journey'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as KnowledgeSlugRouteImport } from './routes/knowledge.$slug'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ProjectsRavenWrapperRouteImport } from './routes/projects.raven-wrapper'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const PdJourneyRoute = PdJourneyRouteImport.update({
  id: '/pd-journey',
  path: '/pd-journey',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeSlugRoute = KnowledgeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KnowledgeRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsRavenWrapperRoute = ProjectsRavenWrapperRouteImport.update({
  id: '/raven-wrapper',
  path: '/raven-wrapper',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/contact': typeof ContactRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/pd-journey': typeof PdJourneyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/resume': typeof ResumeRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/raven-wrapper': typeof ProjectsRavenWrapperRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/contact': typeof ContactRoute
  '/pd-journey': typeof PdJourneyRoute
  '/resume': typeof ResumeRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/raven-wrapper': typeof ProjectsRavenWrapperRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/contact': typeof ContactRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/pd-journey': typeof PdJourneyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/resume': typeof ResumeRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/raven-wrapper': typeof ProjectsRavenWrapperRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activities'
    | '/contact'
    | '/knowledge'
    | '/pd-journey'
    | '/projects'
    | '/resume'
    | '/knowledge/$slug'
    | '/projects/$slug'
    | '/projects/raven-wrapper'
    | '/knowledge/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activities'
    | '/contact'
    | '/pd-journey'
    | '/resume'
    | '/knowledge/$slug'
    | '/projects/$slug'
    | '/projects/raven-wrapper'
    | '/knowledge'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activities'
    | '/contact'
    | '/knowledge'
    | '/pd-journey'
    | '/projects'
    | '/resume'
    | '/knowledge/$slug'
    | '/projects/$slug'
    | '/projects/raven-wrapper'
    | '/knowledge/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivitiesRoute: typeof ActivitiesRoute
  ContactRoute: typeof ContactRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  PdJourneyRoute: typeof PdJourneyRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ResumeRoute: typeof ResumeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pd-journey': {
      id: '/pd-journey'
      path: '/pd-journey'
      fullPath: '/pd-journey'
      preLoaderRoute: typeof PdJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/$slug': {
      id: '/knowledge/$slug'
      path: '/$slug'
      fullPath: '/knowledge/$slug'
      preLoaderRoute: typeof KnowledgeSlugRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/raven-wrapper': {
      id: '/projects/raven-wrapper'
      path: '/raven-wrapper'
      fullPath: '/projects/raven-wrapper'
      preLoaderRoute: typeof ProjectsRavenWrapperRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface KnowledgeRouteChildren {
  KnowledgeSlugRoute: typeof KnowledgeSlugRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeSlugRoute: KnowledgeSlugRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsRavenWrapperRoute: typeof ProjectsRavenWrapperRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsRavenWrapperRoute: ProjectsRavenWrapperRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivitiesRoute: ActivitiesRoute,
  ContactRoute: ContactRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  PdJourneyRoute: PdJourneyRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ResumeRoute: ResumeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
